### ISSUE TITLE
Upgrade ogn-decode and ogn-rf to 0.2.6

### ISSUE THREAD

**Issue by dspreitz** [kerel-fs/pkg-rtlsdr-ogn#1]
Since 1.4. the ogn software version 0.2.6 changed. See http://download.glidernet.org/rpi-gpu/
Presently, the pkg-rtlsdr-ogn is based on an outdated version of the ogn-software, which is now unable to decode Flarm packages.
https://github.com/glidernet/ogn-rf is presently outdated. See https://github.com/glidernet/ogn-rf/issues/28
Replacing ogn-decode and ogn-rf binaries on a system installed from this package results in seg vaults of ofn-decode.

**Comment by kerel-fs** [comment]
Fixed by 18eb03389cb5cea3385cb877476fd13b347e676e: Release version 0.2.61.
